<a href="https://colab.research.google.com/github/zoboro/Python-101/blob/main/7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
NumPy (Numerical Python) is a Python library used for fast numerical computations and working with arrays.

Some of the use cases of Numpy are: array operations, linear algebra, statistical functions, etc.


In [ ]:
import numpy as np

##Array Operations




###Creating Arrays


In [ ]:
##Using a list
arr = np.array([1, 2, 3, 4])

In [ ]:
##Using zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
##Using ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
##Range of numbers
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

###Basic Operations


In [ ]:
##Array Shape
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

##Indexing
##1-D Array
arr = np.array([10, 20, 30, 40])

print(arr[0])

##2-D Array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr[1, 2])

(2, 3)
10
6


####Array Operations

In [ ]:
# Example: An array representing the number of years of experience required for three different data science job listings.
years_of_experience = np.array([1, 2, 3, 4, 5])

In [ ]:
##Addition
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

In [ ]:
##Subtraction
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

In [ ]:
##Multiplication
years_of_experience_double = years_of_experience * 2
years_of_experience_double

array([ 2,  4,  6,  8, 10])

In [ ]:
##Division
years_of_experience_half = years_of_experience / 2
years_of_experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
##Slicing
# Example: Selecting the experience requirement for the second and third job listings.
second_and_third_jobs_experience = years_of_experience[1:3]
second_and_third_jobs_experience

array([2, 3])

In [ ]:
##Boolean Indexing
# Example: Selecting only those job listings that require more than 1 year of experience.
jobs_with_more_than_one_year_exp = years_of_experience[years_of_experience > 2]
jobs_with_more_than_one_year_exp

array([3, 4, 5])

####Mathematical Operations

In [ ]:
arr = np.array([1, 2, 3, 4])

##Sum

print(arr.sum())

##Product

print(arr.prod())

##Cumulative Sum

print(arr.cumsum())

##Cumulative Product

print(arr.cumprod())

10
24
[ 1  3  6 10]
[ 1  2  6 24]


####Statistical Operations

In [ ]:
##Mean

print(arr.mean())

##Maximum

print(arr.max())

##Minimum

print(arr.min())

##Variance

print(arr.var())

##Standard Deviation

print(arr.std())

2.5
4
1
1.25
1.118033988749895
